---
# Use Very Good Venture's linter rules
include: package:very_good_analysis/analysis_options.10.0.0.yaml
linter:
  rules:
    # Except the public API documentation rule
    public_member_api_docs: false